// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package protomodels.person

object PersonProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      protomodels.person.Person,
      protomodels.person.AddressBook
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgxwZXJzb24ucHJvdG8SC3Byb3RvbW9kZWxzIs0CCgZQZXJzb24SHQoEbmFtZRgBIAIoCUIJ4j8GEgRuYW1lUgRuYW1lEhcKA
  mlkGAIgAigFQgfiPwQSAmlkUgJpZBIgCgVlbWFpbBgDIAEoCUIK4j8HEgVlbWFpbFIFZW1haWwSRAoGcGhvbmVzGAQgAygLMh8uc
  HJvdG9tb2RlbHMuUGVyc29uLlBob25lTnVtYmVyQgviPwgSBnBob25lc1IGcGhvbmVzGnYKC1Bob25lTnVtYmVyEiMKBm51bWJlc
  hgBIAIoCUIL4j8IEgZudW1iZXJSBm51bWJlchJCCgR0eXBlGAIgASgOMh0ucHJvdG9tb2RlbHMuUGVyc29uLlBob25lVHlwZToES
  E9NRUIJ4j8GEgR0eXBlUgR0eXBlIisKCVBob25lVHlwZRIKCgZNT0JJTEUQABIICgRIT01FEAESCAoEV09SSxACIkcKC0FkZHJlc
  3NCb29rEjgKBnBlb3BsZRgBIAMoCzITLnByb3RvbW9kZWxzLlBlcnNvbkIL4j8IEgZwZW9wbGVSBnBlb3BsZQ=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}