// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package protomodels.person2

object Person2Proto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      protomodels.person2.Person2,
      protomodels.person2.AddressBook2
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cg1wZXJzb24yLnByb3RvEgtwcm90b21vZGVscyLSAgoHUGVyc29uMhIdCgRuYW1lGAEgAigJQgniPwYSBG5hbWVSBG5hbWUSF
  woCaWQYAiACKAVCB+I/BBICaWRSAmlkEiAKBWVtYWlsGAMgASgJQgriPwcSBWVtYWlsUgVlbWFpbBJGCgZwaG9uZXMYBCADKAsyI
  S5wcm90b21vZGVscy5QZXJzb24yLlBob25lTnVtYmVyMkIL4j8IEgZwaG9uZXNSBnBob25lcxp4CgxQaG9uZU51bWJlcjISIwoGb
  nVtYmVyGAEgAigJQgviPwgSBm51bWJlclIGbnVtYmVyEkMKBHR5cGUYAiABKA4yHi5wcm90b21vZGVscy5QZXJzb24yLlBob25lV
  HlwZToESE9NRUIJ4j8GEgR0eXBlUgR0eXBlIisKCVBob25lVHlwZRIKCgZNT0JJTEUQABIICgRIT01FEAESCAoEV09SSxACIkkKD
  EFkZHJlc3NCb29rMhI5CgZwZW9wbGUYASADKAsyFC5wcm90b21vZGVscy5QZXJzb24yQgviPwgSBnBlb3BsZVIGcGVvcGxl"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}